// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgyesnvppwxlwuspikun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxneWVzbnZwcHd4bHd1c3Bpa3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODE3MDIsImV4cCI6MjA2ODM1NzcwMn0.GS8eU0oFnXaNkBKuhEvJDSlo53m2cGnh1FvYanbQg_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Environment switch: 'supabase' or 'local'
export const BACKEND_MODE = import.meta.env.VITE_BACKEND_MODE || 'supabase';

export const LOCAL_API_URL = import.meta.env.VITE_LOCAL_API_URL || 'http://localhost:5000/api';

// Helper to check if using local API
export const isLocalApi = () => BACKEND_MODE === 'local';